[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Configuração de Flash e PSRAM
board_build.arduino.memory_type = qio_opi ; Quad Flash, Octal PSRAM
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L
board_upload.flash_size = 16MB

build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-s3-psram-cache-issue

monitor_speed = 115200